/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.Cliente;
import Modelo.ClienteDao;
import Modelo.Producto;
import Modelo.ProductoDao;
import Modelo.Proveedor;
import Modelo.ProveedorDao;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author dualbert
 */
public class sistemaPrincipal extends javax.swing.JFrame {

    Cliente cl = new Cliente();
    ClienteDao clDao = new ClienteDao();
    Proveedor pr = new Proveedor();
    ProveedorDao prDao = new ProveedorDao();
    Producto pro = new Producto();
    ProductoDao proDao = new ProductoDao();

    DefaultTableModel modelo = new DefaultTableModel();

    public sistemaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        txtIdCliente.setVisible(false);
        JlabelIdCliente.setVisible(false);
        txtIdProveedor.setVisible(false);
        jLabelIdProveedor.setVisible(false);
        txtIdProducto.setVisible(false);
        jLabelIdProducto.setVisible(false);
        AutoCompleteDecorator.decorate(comboboxProductoProveedor);
        proDao.consultarProveedor(comboboxProductoProveedor);

    }

    public void listarCliente() {
        List<Cliente> listarCL = clDao.listarClientes();
        modelo = (DefaultTableModel) tableCliente.getModel();
        Object[] ob = new Object[6];
        for (int i = 0; i < listarCL.size(); i++) {
            ob[0] = listarCL.get(i).getId();
            ob[1] = listarCL.get(i).getCedula();
            ob[2] = listarCL.get(i).getNombre();
            ob[3] = listarCL.get(i).getTelefono();
            ob[4] = listarCL.get(i).getDireccion();
            ob[5] = listarCL.get(i).getRazon();
            modelo.addRow(ob);
        }
        tableCliente.setModel(modelo);

    }

    public void listarProveedor() {
        //retornamos la lista del proveedor de cliente dao dada por la base de datos
        List<Proveedor> listarPr = prDao.listarProveedor();
        modelo = (DefaultTableModel) tableProveedor.getModel();
        Object[] ob = new Object[6];
        for (int i = 0; i < listarPr.size(); i++) {
            ob[0] = listarPr.get(i).getId();
            ob[1] = listarPr.get(i).getNit();
            ob[2] = listarPr.get(i).getNombre();
            ob[3] = listarPr.get(i).getTelefono();
            ob[4] = listarPr.get(i).getDireccion();
            ob[5] = listarPr.get(i).getRazon();
            modelo.addRow(ob);
        }
        tableProveedor.setModel(modelo);
    }

    public void listarProductos() {
        List<Producto> listarPro = proDao.listarProductos();
        modelo = (DefaultTableModel) tableProducto1.getModel();
        Object[] ob = new Object[6];
        for (int i = 0; i < listarPro.size(); i++) {
            ob[0] = listarPro.get(i).getId();
            ob[1] = listarPro.get(i).getCodigo();
            ob[2] = listarPro.get(i).getNombre();
            ob[3] = listarPro.get(i).getProveedor();
            ob[4] = listarPro.get(i).getStock();
            ob[5] = listarPro.get(i).getPrecio();
            modelo.addRow(ob);
        }
        tableProducto1.setModel(modelo);

    }

    public void limpiarTable() {
        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.removeRow(i);
            i = i - 1;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        BtnIniciarSesion = new javax.swing.JButton();
        jTabbedPane8 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtCodigoVenta = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtDescripcionVenta = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCantidadVenta = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtPrecioVenta = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtStockVenta1 = new javax.swing.JTextField();
        txtStockVenta = new javax.swing.JTextField();
        btnEliminarVenta = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableVenta = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        txtRucVenta = new javax.swing.JTextField();
        txtNombreClienteVenta = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btnImprimirVenta = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        labelTotalapagar = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtIdCliente = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtTelefonoCliente = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtDireccionCliente = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtRazonsocialCliente = new javax.swing.JTextField();
        btnNuevoCliente = new javax.swing.JButton();
        btnEditarCliente = new javax.swing.JButton();
        btnGuardarCliente = new javax.swing.JButton();
        btnEliminarCliente = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableCliente = new javax.swing.JTable();
        JlabelIdCliente = new javax.swing.JLabel();
        txtCedulaCliente = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        txtNitProveedor = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtNombreProveedor = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtTelefonoProveedor = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtDireccionProveedor = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtRazonsocialProveedor = new javax.swing.JTextField();
        btnNuevoProveedor = new javax.swing.JButton();
        btnEditarProveedor = new javax.swing.JButton();
        btnGuardarProveedor = new javax.swing.JButton();
        btnEliminarProveedor = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableProveedor = new javax.swing.JTable();
        txtIdProveedor = new javax.swing.JTextField();
        jLabelIdProveedor = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnPDfVenta = new javax.swing.JButton();
        txtIdVenta = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        TableGenerarVenta = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        txtCodigoProducto = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtDescripcionProducto = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtCantidadProducto = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtPrecioProducto = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        comboboxProductoProveedor = new javax.swing.JComboBox<>();
        btnNuevoProducto = new javax.swing.JButton();
        btnEditarProducto = new javax.swing.JButton();
        btnGuardarProducto = new javax.swing.JButton();
        btnEliminarProducto = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableProducto1 = new javax.swing.JTable();
        txtIdProducto = new javax.swing.JTextField();
        jLabelIdProducto = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(86, 89, 156));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/logo login.png"))); // NOI18N

        jButton4.setBackground(new java.awt.Color(86, 89, 156));
        jButton4.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Ventas ");
        jButton4.setBorder(null);
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(86, 89, 156));
        jButton5.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Nueva Venta ");
        jButton5.setBorder(null);
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(86, 89, 156));
        jButton6.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Clientes");
        jButton6.setBorder(null);
        jButton6.setContentAreaFilled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(86, 89, 156));
        jButton7.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Proveedores ");
        jButton7.setBorder(null);
        jButton7.setContentAreaFilled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(86, 89, 156));
        jButton8.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Productos");
        jButton8.setBorder(null);
        jButton8.setContentAreaFilled(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        BtnIniciarSesion.setText("Iniciar Sesion");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(jButton5)
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addGap(18, 18, 18)
                .addComponent(jButton7)
                .addGap(18, 18, 18)
                .addComponent(jButton8)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(257, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnIniciarSesion)
                .addGap(45, 45, 45))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(BtnIniciarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton7)
                    .addComponent(jButton8)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 137, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jLabel8.setBackground(new java.awt.Color(204, 204, 204));
        jLabel8.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("Codigo*");

        txtCodigoVenta.setBackground(new java.awt.Color(204, 204, 204));
        txtCodigoVenta.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtCodigoVenta.setForeground(new java.awt.Color(102, 102, 102));
        txtCodigoVenta.setToolTipText("");
        txtCodigoVenta.setPreferredSize(new java.awt.Dimension(235, 33));
        txtCodigoVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoVentaActionPerformed(evt);
            }
        });
        txtCodigoVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoVentaKeyPressed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(204, 204, 204));
        jLabel9.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setText("Descripcion");

        txtDescripcionVenta.setEditable(false);
        txtDescripcionVenta.setBackground(new java.awt.Color(204, 204, 204));
        txtDescripcionVenta.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtDescripcionVenta.setForeground(new java.awt.Color(102, 102, 102));
        txtDescripcionVenta.setToolTipText("");
        txtDescripcionVenta.setPreferredSize(new java.awt.Dimension(235, 33));

        jLabel10.setBackground(new java.awt.Color(204, 204, 204));
        jLabel10.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("Cantidad*");

        txtCantidadVenta.setBackground(new java.awt.Color(204, 204, 204));
        txtCantidadVenta.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtCantidadVenta.setForeground(new java.awt.Color(102, 102, 102));
        txtCantidadVenta.setToolTipText("");
        txtCantidadVenta.setPreferredSize(new java.awt.Dimension(235, 33));

        jLabel11.setBackground(new java.awt.Color(204, 204, 204));
        jLabel11.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setText("Precio");

        txtPrecioVenta.setEditable(false);
        txtPrecioVenta.setBackground(new java.awt.Color(204, 204, 204));
        txtPrecioVenta.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtPrecioVenta.setForeground(new java.awt.Color(102, 102, 102));
        txtPrecioVenta.setToolTipText("");
        txtPrecioVenta.setPreferredSize(new java.awt.Dimension(235, 33));

        jLabel12.setBackground(new java.awt.Color(204, 204, 204));
        jLabel12.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 153, 153));
        jLabel12.setText("Cantidad Disponible");

        txtStockVenta1.setEditable(false);
        txtStockVenta1.setBackground(new java.awt.Color(204, 204, 204));
        txtStockVenta1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtStockVenta1.setForeground(new java.awt.Color(102, 102, 102));
        txtStockVenta1.setToolTipText("");
        txtStockVenta1.setPreferredSize(new java.awt.Dimension(235, 33));

        txtStockVenta.setEditable(false);
        txtStockVenta.setBackground(new java.awt.Color(204, 204, 204));
        txtStockVenta.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtStockVenta.setForeground(new java.awt.Color(102, 102, 102));
        txtStockVenta.setToolTipText("");
        txtStockVenta.setPreferredSize(new java.awt.Dimension(235, 33));

        btnEliminarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/eliminar2.png"))); // NOI18N
        btnEliminarVenta.setBorder(null);
        btnEliminarVenta.setBorderPainted(false);
        btnEliminarVenta.setContentAreaFilled(false);

        tableVenta.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        tableVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CANTIDAD", "DESCRIPCION", "PRECIO", "TOTAL"
            }
        ));
        tableVenta.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(tableVenta);

        jLabel13.setBackground(new java.awt.Color(204, 204, 204));
        jLabel13.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 153, 153));
        jLabel13.setText("Rut/Dni");

        txtRucVenta.setEditable(false);
        txtRucVenta.setBackground(new java.awt.Color(204, 204, 204));
        txtRucVenta.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtRucVenta.setForeground(new java.awt.Color(102, 102, 102));
        txtRucVenta.setToolTipText("");
        txtRucVenta.setPreferredSize(new java.awt.Dimension(235, 33));

        txtNombreClienteVenta.setEditable(false);
        txtNombreClienteVenta.setBackground(new java.awt.Color(204, 204, 204));
        txtNombreClienteVenta.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtNombreClienteVenta.setForeground(new java.awt.Color(102, 102, 102));
        txtNombreClienteVenta.setToolTipText("");
        txtNombreClienteVenta.setPreferredSize(new java.awt.Dimension(235, 33));

        jLabel14.setBackground(new java.awt.Color(204, 204, 204));
        jLabel14.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 153, 153));
        jLabel14.setText("Nombre");

        btnImprimirVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/imprimir2.png"))); // NOI18N
        btnImprimirVenta.setBorder(null);
        btnImprimirVenta.setBorderPainted(false);
        btnImprimirVenta.setContentAreaFilled(false);

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Total a Pagar:");

        labelTotalapagar.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        labelTotalapagar.setForeground(new java.awt.Color(102, 102, 102));
        labelTotalapagar.setText("---");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(110, 110, 110)
                .addComponent(jLabel10)
                .addGap(56, 56, 56)
                .addComponent(jLabel11)
                .addGap(411, 411, 411))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addComponent(txtCodigoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(txtDescripcionVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(txtCantidadVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12)
                                .addComponent(txtStockVenta1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(10, 10, 10)
                            .addComponent(txtStockVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(btnEliminarVenta))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 903, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13)
                                .addComponent(txtRucVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(10, 10, 10)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel14)
                                .addComponent(txtNombreClienteVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(50, 50, 50)
                            .addComponent(btnImprimirVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(140, 140, 140)
                            .addComponent(jLabel2)
                            .addGap(16, 16, 16)
                            .addComponent(labelTotalapagar)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addContainerGap(321, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addComponent(txtCodigoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addComponent(txtDescripcionVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addComponent(txtCantidadVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(txtPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel12)
                            .addGap(2, 2, 2)
                            .addComponent(txtStockVenta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(txtStockVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnEliminarVenta))
                    .addGap(16, 16, 16)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(20, 20, 20)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addGap(2, 2, 2)
                            .addComponent(txtRucVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addGap(2, 2, 2)
                            .addComponent(txtNombreClienteVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnImprimirVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(labelTotalapagar))))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane8.addTab("Nueva Venta", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setBackground(new java.awt.Color(204, 204, 204));
        jLabel15.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 153, 153));
        jLabel15.setText("Cedula*");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 21, -1, -1));

        txtIdCliente.setBackground(new java.awt.Color(204, 204, 204));
        txtIdCliente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtIdCliente.setForeground(new java.awt.Color(102, 102, 102));
        txtIdCliente.setToolTipText("");
        txtIdCliente.setPreferredSize(new java.awt.Dimension(235, 33));
        jPanel4.add(txtIdCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 49, 53, -1));

        jLabel16.setBackground(new java.awt.Color(204, 204, 204));
        jLabel16.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(153, 153, 153));
        jLabel16.setText("Nombre* ");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 90, -1, -1));

        txtNombreCliente.setBackground(new java.awt.Color(204, 204, 204));
        txtNombreCliente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtNombreCliente.setForeground(new java.awt.Color(102, 102, 102));
        txtNombreCliente.setToolTipText("");
        txtNombreCliente.setPreferredSize(new java.awt.Dimension(235, 33));
        jPanel4.add(txtNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 114, 160, -1));

        jLabel17.setBackground(new java.awt.Color(204, 204, 204));
        jLabel17.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(153, 153, 153));
        jLabel17.setText("Telefono*");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 159, -1, -1));

        txtTelefonoCliente.setBackground(new java.awt.Color(204, 204, 204));
        txtTelefonoCliente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtTelefonoCliente.setForeground(new java.awt.Color(102, 102, 102));
        txtTelefonoCliente.setToolTipText("");
        txtTelefonoCliente.setPreferredSize(new java.awt.Dimension(235, 33));
        jPanel4.add(txtTelefonoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 180, 160, -1));

        jLabel18.setBackground(new java.awt.Color(204, 204, 204));
        jLabel18.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(153, 153, 153));
        jLabel18.setText("Direccion*");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 225, -1, -1));

        txtDireccionCliente.setBackground(new java.awt.Color(204, 204, 204));
        txtDireccionCliente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtDireccionCliente.setForeground(new java.awt.Color(102, 102, 102));
        txtDireccionCliente.setToolTipText("");
        txtDireccionCliente.setPreferredSize(new java.awt.Dimension(235, 33));
        jPanel4.add(txtDireccionCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 246, 160, -1));

        jLabel19.setBackground(new java.awt.Color(204, 204, 204));
        jLabel19.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(153, 153, 153));
        jLabel19.setText("Razon Social*");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 291, -1, -1));

        txtRazonsocialCliente.setBackground(new java.awt.Color(204, 204, 204));
        txtRazonsocialCliente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtRazonsocialCliente.setForeground(new java.awt.Color(102, 102, 102));
        txtRazonsocialCliente.setToolTipText("");
        txtRazonsocialCliente.setPreferredSize(new java.awt.Dimension(235, 33));
        jPanel4.add(txtRazonsocialCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 312, 160, -1));

        btnNuevoCliente.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnNuevoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/nuevo-documento.png"))); // NOI18N
        btnNuevoCliente.setText("Nuevo");
        btnNuevoCliente.setBorderPainted(false);
        btnNuevoCliente.setContentAreaFilled(false);
        btnNuevoCliente.setDoubleBuffered(true);
        btnNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoClienteActionPerformed(evt);
            }
        });
        jPanel4.add(btnNuevoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 142, 103, -1));

        btnEditarCliente.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnEditarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/editar.png"))); // NOI18N
        btnEditarCliente.setText("editar ");
        btnEditarCliente.setBorderPainted(false);
        btnEditarCliente.setContentAreaFilled(false);
        btnEditarCliente.setDoubleBuffered(true);
        btnEditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarClienteActionPerformed(evt);
            }
        });
        jPanel4.add(btnEditarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 192, 103, -1));

        btnGuardarCliente.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnGuardarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/salvar2.png"))); // NOI18N
        btnGuardarCliente.setText("guardar");
        btnGuardarCliente.setBorderPainted(false);
        btnGuardarCliente.setContentAreaFilled(false);
        btnGuardarCliente.setDoubleBuffered(true);
        btnGuardarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarClienteActionPerformed(evt);
            }
        });
        jPanel4.add(btnGuardarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 142, -1, -1));

        btnEliminarCliente.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnEliminarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/borrar.png"))); // NOI18N
        btnEliminarCliente.setText("eliminar ");
        btnEliminarCliente.setBorderPainted(false);
        btnEliminarCliente.setContentAreaFilled(false);
        btnEliminarCliente.setDoubleBuffered(true);
        btnEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarClienteActionPerformed(evt);
            }
        });
        jPanel4.add(btnEliminarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 192, -1, -1));

        tableCliente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        tableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "CEDULA", "NOMBRE", "TELEFONO", "DIRECCION", "RAZON SOCIAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableClienteMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableCliente);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 6, 538, 364));

        JlabelIdCliente.setBackground(new java.awt.Color(204, 204, 204));
        JlabelIdCliente.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        JlabelIdCliente.setForeground(new java.awt.Color(153, 153, 153));
        JlabelIdCliente.setText("Id*");
        jPanel4.add(JlabelIdCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 21, -1, -1));

        txtCedulaCliente.setBackground(new java.awt.Color(204, 204, 204));
        txtCedulaCliente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtCedulaCliente.setForeground(new java.awt.Color(102, 102, 102));
        txtCedulaCliente.setToolTipText("");
        txtCedulaCliente.setPreferredSize(new java.awt.Dimension(235, 33));
        jPanel4.add(txtCedulaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 49, 160, -1));

        jTabbedPane8.addTab("Clientes", jPanel4);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setBackground(new java.awt.Color(204, 204, 204));
        jLabel20.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(153, 153, 153));
        jLabel20.setText("Nit*");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 21, -1, -1));

        txtNitProveedor.setBackground(new java.awt.Color(204, 204, 204));
        txtNitProveedor.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtNitProveedor.setForeground(new java.awt.Color(102, 102, 102));
        txtNitProveedor.setToolTipText("");
        txtNitProveedor.setPreferredSize(new java.awt.Dimension(235, 33));
        jPanel5.add(txtNitProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 45, 160, -1));

        jLabel21.setBackground(new java.awt.Color(204, 204, 204));
        jLabel21.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(153, 153, 153));
        jLabel21.setText("Nombre* ");
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 90, -1, -1));

        txtNombreProveedor.setBackground(new java.awt.Color(204, 204, 204));
        txtNombreProveedor.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtNombreProveedor.setForeground(new java.awt.Color(102, 102, 102));
        txtNombreProveedor.setToolTipText("");
        txtNombreProveedor.setPreferredSize(new java.awt.Dimension(235, 33));
        jPanel5.add(txtNombreProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 114, 160, -1));

        jLabel22.setBackground(new java.awt.Color(204, 204, 204));
        jLabel22.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(153, 153, 153));
        jLabel22.setText("Telefono*");
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 159, -1, -1));

        txtTelefonoProveedor.setBackground(new java.awt.Color(204, 204, 204));
        txtTelefonoProveedor.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtTelefonoProveedor.setForeground(new java.awt.Color(102, 102, 102));
        txtTelefonoProveedor.setToolTipText("");
        txtTelefonoProveedor.setPreferredSize(new java.awt.Dimension(235, 33));
        jPanel5.add(txtTelefonoProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 180, 160, -1));

        jLabel23.setBackground(new java.awt.Color(204, 204, 204));
        jLabel23.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(153, 153, 153));
        jLabel23.setText("Direccion*");
        jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 225, -1, -1));

        txtDireccionProveedor.setBackground(new java.awt.Color(204, 204, 204));
        txtDireccionProveedor.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtDireccionProveedor.setForeground(new java.awt.Color(102, 102, 102));
        txtDireccionProveedor.setToolTipText("");
        txtDireccionProveedor.setPreferredSize(new java.awt.Dimension(235, 33));
        jPanel5.add(txtDireccionProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 246, 160, -1));

        jLabel24.setBackground(new java.awt.Color(204, 204, 204));
        jLabel24.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(153, 153, 153));
        jLabel24.setText("Razon Social*");
        jPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 291, -1, -1));

        txtRazonsocialProveedor.setBackground(new java.awt.Color(204, 204, 204));
        txtRazonsocialProveedor.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtRazonsocialProveedor.setForeground(new java.awt.Color(102, 102, 102));
        txtRazonsocialProveedor.setToolTipText("");
        txtRazonsocialProveedor.setPreferredSize(new java.awt.Dimension(235, 33));
        jPanel5.add(txtRazonsocialProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 312, 160, -1));

        btnNuevoProveedor.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnNuevoProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/nuevo-documento.png"))); // NOI18N
        btnNuevoProveedor.setText("Nuevo");
        btnNuevoProveedor.setBorderPainted(false);
        btnNuevoProveedor.setContentAreaFilled(false);
        btnNuevoProveedor.setDoubleBuffered(true);
        btnNuevoProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoProveedorActionPerformed(evt);
            }
        });
        jPanel5.add(btnNuevoProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 142, 103, -1));

        btnEditarProveedor.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnEditarProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/editar.png"))); // NOI18N
        btnEditarProveedor.setText("editar ");
        btnEditarProveedor.setBorderPainted(false);
        btnEditarProveedor.setContentAreaFilled(false);
        btnEditarProveedor.setDoubleBuffered(true);
        btnEditarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarProveedorActionPerformed(evt);
            }
        });
        jPanel5.add(btnEditarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 192, 103, -1));

        btnGuardarProveedor.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnGuardarProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/salvar2.png"))); // NOI18N
        btnGuardarProveedor.setText("guardar");
        btnGuardarProveedor.setBorderPainted(false);
        btnGuardarProveedor.setContentAreaFilled(false);
        btnGuardarProveedor.setDoubleBuffered(true);
        btnGuardarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarProveedorActionPerformed(evt);
            }
        });
        jPanel5.add(btnGuardarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 142, -1, -1));

        btnEliminarProveedor.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnEliminarProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/borrar.png"))); // NOI18N
        btnEliminarProveedor.setText("eliminar ");
        btnEliminarProveedor.setBorderPainted(false);
        btnEliminarProveedor.setContentAreaFilled(false);
        btnEliminarProveedor.setDoubleBuffered(true);
        btnEliminarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProveedorActionPerformed(evt);
            }
        });
        jPanel5.add(btnEliminarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 192, -1, -1));

        tableProveedor.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        tableProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NIT", "NOMBRE", "TELEFONO", "DIRECCION", "RAZON SOCIAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableProveedor.setAlignmentX(1.0F);
        tableProveedor.setAlignmentY(1.0F);
        tableProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableProveedorMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableProveedor);

        jPanel5.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 6, 537, 364));

        txtIdProveedor.setBackground(new java.awt.Color(204, 204, 204));
        txtIdProveedor.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtIdProveedor.setForeground(new java.awt.Color(102, 102, 102));
        txtIdProveedor.setToolTipText("");
        txtIdProveedor.setPreferredSize(new java.awt.Dimension(235, 33));
        jPanel5.add(txtIdProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 45, 53, -1));

        jLabelIdProveedor.setBackground(new java.awt.Color(204, 204, 204));
        jLabelIdProveedor.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabelIdProveedor.setForeground(new java.awt.Color(153, 153, 153));
        jLabelIdProveedor.setText("Id*");
        jPanel5.add(jLabelIdProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 17, -1, -1));

        jTabbedPane8.addTab("Proveedores", jPanel5);

        btnPDfVenta.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnPDfVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/pdf2.png"))); // NOI18N
        btnPDfVenta.setToolTipText("");
        btnPDfVenta.setBorderPainted(false);
        btnPDfVenta.setContentAreaFilled(false);

        txtIdVenta.setBackground(new java.awt.Color(204, 204, 204));
        txtIdVenta.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtIdVenta.setForeground(new java.awt.Color(102, 102, 102));
        txtIdVenta.setToolTipText("");
        txtIdVenta.setPreferredSize(new java.awt.Dimension(235, 33));

        jLabel30.setBackground(new java.awt.Color(204, 204, 204));
        jLabel30.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(153, 153, 153));
        jLabel30.setText("id*");

        TableGenerarVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "CLIENTE", "VENDEDOR ", "TOTAL"
            }
        ));
        jScrollPane5.setViewportView(TableGenerarVenta);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 965, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btnPDfVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPDfVenta, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane8.addTab("Ventas", jPanel6);

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setBackground(new java.awt.Color(204, 204, 204));
        jLabel25.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(153, 153, 153));
        jLabel25.setText("Codigo*");
        jPanel7.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 21, -1, -1));

        txtCodigoProducto.setBackground(new java.awt.Color(204, 204, 204));
        txtCodigoProducto.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtCodigoProducto.setForeground(new java.awt.Color(102, 102, 102));
        txtCodigoProducto.setToolTipText("");
        txtCodigoProducto.setPreferredSize(new java.awt.Dimension(235, 33));
        jPanel7.add(txtCodigoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 45, 160, -1));

        jLabel26.setBackground(new java.awt.Color(204, 204, 204));
        jLabel26.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(153, 153, 153));
        jLabel26.setText("Descripcion*");
        jPanel7.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 90, -1, -1));

        txtDescripcionProducto.setBackground(new java.awt.Color(204, 204, 204));
        txtDescripcionProducto.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtDescripcionProducto.setForeground(new java.awt.Color(102, 102, 102));
        txtDescripcionProducto.setToolTipText("");
        txtDescripcionProducto.setPreferredSize(new java.awt.Dimension(235, 33));
        jPanel7.add(txtDescripcionProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 114, 160, -1));

        jLabel27.setBackground(new java.awt.Color(204, 204, 204));
        jLabel27.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(153, 153, 153));
        jLabel27.setText("Cantidad*");
        jPanel7.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 159, -1, -1));

        txtCantidadProducto.setBackground(new java.awt.Color(204, 204, 204));
        txtCantidadProducto.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtCantidadProducto.setForeground(new java.awt.Color(102, 102, 102));
        txtCantidadProducto.setToolTipText("");
        txtCantidadProducto.setPreferredSize(new java.awt.Dimension(235, 33));
        jPanel7.add(txtCantidadProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 180, 160, -1));

        jLabel28.setBackground(new java.awt.Color(204, 204, 204));
        jLabel28.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(153, 153, 153));
        jLabel28.setText("Precio*");
        jPanel7.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 225, -1, -1));

        txtPrecioProducto.setBackground(new java.awt.Color(204, 204, 204));
        txtPrecioProducto.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtPrecioProducto.setForeground(new java.awt.Color(102, 102, 102));
        txtPrecioProducto.setToolTipText("");
        txtPrecioProducto.setPreferredSize(new java.awt.Dimension(235, 33));
        jPanel7.add(txtPrecioProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 246, 160, -1));

        jLabel29.setBackground(new java.awt.Color(204, 204, 204));
        jLabel29.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(153, 153, 153));
        jLabel29.setText("Proveedor");
        jPanel7.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 291, -1, -1));

        comboboxProductoProveedor.setBackground(new java.awt.Color(204, 204, 204));
        comboboxProductoProveedor.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        comboboxProductoProveedor.setForeground(new java.awt.Color(102, 102, 102));
        comboboxProductoProveedor.setMinimumSize(new java.awt.Dimension(235, 33));
        comboboxProductoProveedor.setPreferredSize(new java.awt.Dimension(235, 33));
        comboboxProductoProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxProductoProveedorActionPerformed(evt);
            }
        });
        jPanel7.add(comboboxProductoProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 315, 160, -1));

        btnNuevoProducto.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnNuevoProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/nuevo-documento.png"))); // NOI18N
        btnNuevoProducto.setText("Nuevo");
        btnNuevoProducto.setBorderPainted(false);
        btnNuevoProducto.setContentAreaFilled(false);
        btnNuevoProducto.setDoubleBuffered(true);
        btnNuevoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoProductoActionPerformed(evt);
            }
        });
        jPanel7.add(btnNuevoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 142, 103, -1));

        btnEditarProducto.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnEditarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/editar.png"))); // NOI18N
        btnEditarProducto.setText("editar ");
        btnEditarProducto.setBorderPainted(false);
        btnEditarProducto.setContentAreaFilled(false);
        btnEditarProducto.setDoubleBuffered(true);
        btnEditarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarProductoActionPerformed(evt);
            }
        });
        jPanel7.add(btnEditarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 103, -1));

        btnGuardarProducto.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnGuardarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/salvar2.png"))); // NOI18N
        btnGuardarProducto.setText("guardar");
        btnGuardarProducto.setBorderPainted(false);
        btnGuardarProducto.setContentAreaFilled(false);
        btnGuardarProducto.setDoubleBuffered(true);
        btnGuardarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarProductoActionPerformed(evt);
            }
        });
        jPanel7.add(btnGuardarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, -1, -1));

        btnEliminarProducto.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnEliminarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/borrar.png"))); // NOI18N
        btnEliminarProducto.setText("eliminar ");
        btnEliminarProducto.setBorderPainted(false);
        btnEliminarProducto.setContentAreaFilled(false);
        btnEliminarProducto.setDoubleBuffered(true);
        btnEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProductoActionPerformed(evt);
            }
        });
        jPanel7.add(btnEliminarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 192, -1, -1));

        tableProducto1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        tableProducto1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "CODIGO", "DESCRIPCION", "PROVEEDOR", "CANTIDAD", "PRECIO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableProducto1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableProducto1MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tableProducto1);

        jPanel7.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 6, 473, 364));

        txtIdProducto.setBackground(new java.awt.Color(204, 204, 204));
        txtIdProducto.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtIdProducto.setForeground(new java.awt.Color(102, 102, 102));
        txtIdProducto.setToolTipText("");
        txtIdProducto.setPreferredSize(new java.awt.Dimension(235, 33));
        jPanel7.add(txtIdProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 45, 53, -1));

        jLabelIdProducto.setBackground(new java.awt.Color(204, 204, 204));
        jLabelIdProducto.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabelIdProducto.setForeground(new java.awt.Color(153, 153, 153));
        jLabelIdProducto.setText("Id*");
        jPanel7.add(jLabelIdProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 17, -1, -1));

        jTabbedPane8.addTab("productos", jPanel7);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 977, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 376, Short.MAX_VALUE)
        );

        jTabbedPane8.addTab("tab6", jPanel8);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane8)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane8)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        limpiarTable();
        listarCliente();
        jTabbedPane8.setSelectedIndex(1);

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        limpiarTable();
        listarProveedor();
        jTabbedPane8.setSelectedIndex(2);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        limpiarTable();
        listarProductos();
        jTabbedPane8.setSelectedIndex(4);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void btnGuardarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarClienteActionPerformed
        if (!"".equals(txtIdCliente.getText()) || !"".equals(txtNombreCliente.getText()) || !"".equals(txtTelefonoCliente.getText()) || !"".equals(txtDireccionCliente.getText()) || !"".equals(txtRazonsocialCliente.getText())) {
            cl.setCedula(txtNombreCliente.getText());
            cl.setNombre(txtNombreCliente.getText());
            cl.setTelefono(txtTelefonoCliente.getText());
            cl.setDireccion(txtDireccionCliente.getText());
            cl.setRazon(txtRazonsocialCliente.getText());
            clDao.RegistrarCliente(cl);
            JOptionPane.showMessageDialog(null, "Cliente registrado con exito");
            limpiarTable();
            listarCliente();
            limpiarCamposCliente();
        } else {
            JOptionPane.showMessageDialog(null, "algunos campos estan vacios o mal escritos");
        }
    }//GEN-LAST:event_btnGuardarClienteActionPerformed

    private void btnEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarClienteActionPerformed
        if (!"".equals(txtIdCliente.getText())) {
            int pregunta = JOptionPane.showConfirmDialog(null, "¿Estas seguro que desea eliminar este cliente?");
            if (pregunta == 0) {
                int id = Integer.parseInt(txtIdCliente.getText());
                clDao.EliminarCliente(id);
                limpiarTable();
                listarCliente();
                limpiarCamposCliente();

            }
        }
    }//GEN-LAST:event_btnEliminarClienteActionPerformed

    private void tableClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableClienteMouseClicked
        int fila = tableCliente.rowAtPoint(evt.getPoint());
        txtIdCliente.setText(tableCliente.getValueAt(fila, 0).toString());
        txtCedulaCliente.setText(tableCliente.getValueAt(fila, 1).toString());
        txtNombreCliente.setText(tableCliente.getValueAt(fila, 2).toString());
        txtTelefonoCliente.setText(tableCliente.getValueAt(fila, 3).toString());
        txtDireccionCliente.setText(tableCliente.getValueAt(fila, 4).toString());
        txtRazonsocialCliente.setText(tableCliente.getValueAt(fila, 5).toString());
    }//GEN-LAST:event_tableClienteMouseClicked

    private void comboboxProductoProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxProductoProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboboxProductoProveedorActionPerformed

    private void btnGuardarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarProductoActionPerformed
        if (!"".equals(txtCodigoProducto.getText()) || !"".equals(txtDescripcionProducto.getText()) || !"".equals(comboboxProductoProveedor.getSelectedIndex()) || !"".equals(txtCantidadProducto.getText()) || !"".equals(txtPrecioProducto.getText())) {
            pro.setCodigo(txtCodigoProducto.getText());
            pro.setNombre(txtDescripcionProducto.getText());
            pro.setProveedor(String.valueOf(comboboxProductoProveedor.getSelectedItem().toString()));
            pro.setStock(Integer.parseInt(txtCantidadProducto.getText()));
            pro.setPrecio(Double.parseDouble(txtPrecioProducto.getText()));
            proDao.registrarProducto(pro);
            JOptionPane.showMessageDialog(null, "Producto registrado con exito.");
            limpiarTable();
            listarProductos();
            limpiarCamposProductos();
        } else {
            JOptionPane.showMessageDialog(null, "uno o algunos campos estan vacios");
        }
    }//GEN-LAST:event_btnGuardarProductoActionPerformed

    private void btnEditarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarProveedorActionPerformed
        if ("".equals(txtIdProveedor.getText())) {
            JOptionPane.showMessageDialog(null, "Seleccione un Proveedor");
        } else {
            if (!"".equals(txtNitProveedor.getText()) || !"".equals(txtNombreProveedor.getText()) || !"".equals(txtTelefonoProveedor.getText()) || !"".equals(txtDireccionProveedor.getText()) || !"".equals(txtRazonsocialProveedor.getText())) {
                pr.setNit(txtNitProveedor.getText());
                pr.setNombre(txtNombreProveedor.getText());
                pr.setTelefono(txtTelefonoProveedor.getText());
                pr.setDireccion(txtDireccionProveedor.getText());
                pr.setRazon(txtRazonsocialProveedor.getText());
                pr.setId(Integer.parseInt(txtIdProveedor.getText()));
                prDao.ModificarProveedor(pr);
                JOptionPane.showMessageDialog(null, "Proveedor registrado con exito");
                limpiarTable();
                listarProveedor();
                limpiarCamposProveedor();
            }
        }
    }//GEN-LAST:event_btnEditarProveedorActionPerformed

    private void btnGuardarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarProveedorActionPerformed
        if (!"".equals(txtNitProveedor.getText()) || !"".equals(txtNombreProveedor.getText()) || !"".equals(txtTelefonoProveedor.getText()) || !"".equals(txtDireccionProveedor.getText()) || !"".equals(txtRazonsocialProveedor.getText())) {

            pr.setNit(txtNitProveedor.getText());
            pr.setNombre(txtNombreProveedor.getText());
            pr.setTelefono(txtTelefonoCliente.getText());
            pr.setDireccion(txtDireccionProveedor.getText());
            pr.setRazon(txtRazonsocialProveedor.getText());
            prDao.registraProveedor(pr);
            JOptionPane.showMessageDialog(null, "Proveedor registrado con exito");
            limpiarTable();
        } else {
            JOptionPane.showMessageDialog(null, "Algunos campos estan vacios o mal escritos");
        }
    }//GEN-LAST:event_btnGuardarProveedorActionPerformed

    private void btnEliminarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProveedorActionPerformed
        if (!"".equals(txtIdProveedor.getText())) {
            int pregunta = JOptionPane.showConfirmDialog(null, "¿Estas seguro que desea eliminar este cliente?");
            if (pregunta == 0) {
                int id = Integer.parseInt(txtIdProveedor.getText());
                prDao.eliminarProveedor(id);
                limpiarTable();
                listarProveedor();
                limpiarCamposProveedor();
            }
        }
    }//GEN-LAST:event_btnEliminarProveedorActionPerformed

    private void tableProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableProveedorMouseClicked
        int fila = tableCliente.rowAtPoint(evt.getPoint());
        txtIdProveedor.setText(tableProveedor.getValueAt(fila, 0).toString());
        txtNitProveedor.setText(tableProveedor.getValueAt(fila, 1).toString());
        txtNombreProveedor.setText(tableProveedor.getValueAt(fila, 2).toString());
        txtTelefonoProveedor.setText(tableProveedor.getValueAt(fila, 3).toString());
        txtDireccionProveedor.setText(tableProveedor.getValueAt(fila, 4).toString());
        txtRazonsocialProveedor.setText(tableProveedor.getValueAt(fila, 5).toString());
    }//GEN-LAST:event_tableProveedorMouseClicked

    private void btnEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarClienteActionPerformed
        if ("".equals(txtIdCliente.getText())) {
            JOptionPane.showMessageDialog(null, "Selecione un Cliente");
        } else {

            if (!"".equals(txtCedulaCliente.getText()) && !"".equals(txtNombreCliente.getText()) && !"".equals(txtTelefonoCliente.getText()) && !"".equals(txtDireccionCliente.getText()) && !"".equals(txtRazonsocialCliente.getText())) {
                cl.setCedula(txtCedulaCliente.getText());
                cl.setNombre(txtNombreCliente.getText());
                cl.setTelefono(txtTelefonoCliente.getText());
                cl.setDireccion(txtDireccionCliente.getText());
                cl.setRazon(txtRazonsocialCliente.getText());
                cl.setId(Integer.parseInt(txtIdCliente.getText()));
                clDao.ModificarCliente(cl);
                limpiarTable();
                JOptionPane.showMessageDialog(null, "Cliente Actualizado con exito");
                limpiarCamposCliente();
                listarCliente();
            } else {
                JOptionPane.showMessageDialog(null, "uno o varios campos estan vacios");
            }
        }
    }//GEN-LAST:event_btnEditarClienteActionPerformed

    private void btnNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoClienteActionPerformed
        limpiarCamposCliente();
        txtCedulaCliente.requestFocus();
    }//GEN-LAST:event_btnNuevoClienteActionPerformed

    private void btnNuevoProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoProveedorActionPerformed
        limpiarCamposProveedor();
        txtNitProveedor.requestFocus();
    }//GEN-LAST:event_btnNuevoProveedorActionPerformed

    private void btnEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProductoActionPerformed
        if (!"".equals(txtIdProducto.getText())) {
            int pregunta = JOptionPane.showConfirmDialog(null, "¿Seguro que quiere eliminar este Producto?");

            if (pregunta == 0) {
                int id = Integer.parseInt(txtIdProducto.getText());
                proDao.eliminarProducto(id);
                limpiarTable();
                listarProductos();
                limpiarCamposProductos();
            }
        } else {

        }
    }//GEN-LAST:event_btnEliminarProductoActionPerformed

    private void tableProducto1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableProducto1MouseClicked
        int fila = tableProducto1.rowAtPoint(evt.getPoint());
        txtIdProducto.setText(tableProducto1.getValueAt(fila, 0).toString());
        txtCodigoProducto.setText(tableProducto1.getValueAt(fila, 1).toString());
        txtDescripcionProducto.setText(tableProducto1.getValueAt(fila, 2).toString());
        comboboxProductoProveedor.setSelectedItem(tableProducto1.getValueAt(fila, 3).toString());
        txtCantidadProducto.setText(tableProducto1.getValueAt(fila, 4).toString());
        txtPrecioProducto.setText(tableProducto1.getValueAt(fila, 5).toString());

    }//GEN-LAST:event_tableProducto1MouseClicked

    private void btnEditarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarProductoActionPerformed
        if ("".equals(txtIdProducto.getText())) {
            JOptionPane.showMessageDialog(null, "Selecciona un proveedor");
        } else {
            if (!"".equals(txtCodigoProducto.getText()) || !"".equals(txtDescripcionProducto.getText()) || !"".equals(comboboxProductoProveedor.getSelectedItem().toString()) || !"".equals(txtCantidadProducto.getText()) || !"".equals(txtPrecioProducto.getText())) {

                pro.setCodigo(txtCodigoProducto.getText());
                pro.setNombre(txtDescripcionProducto.getText());
                pro.setProveedor(comboboxProductoProveedor.getSelectedItem().toString());
                pro.setStock(Integer.parseInt(txtCantidadProducto.getText()));
                pro.setPrecio(Double.parseDouble(txtPrecioProducto.getText()));
                pro.setId(Integer.parseInt(txtIdProducto.getText()));
                proDao.modificarProducto(pro);
                limpiarTable();
                limpiarCamposProductos();
                JOptionPane.showMessageDialog(null, "Producto actualizado con exito");
                listarProductos();
            } else {
                JOptionPane.showMessageDialog(null, "Uno o varios campos estan vacios");
            }

        }
    }//GEN-LAST:event_btnEditarProductoActionPerformed

    private void txtCodigoVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoVentaActionPerformed

    private void txtCodigoVentaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoVentaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!"".equals(txtCodigoVenta.getText())) {

                pro = proDao.BuscarProducto(txtCodigoVenta.getText());
                if (pro.getNombre() != null) {
                    txtDescripcionVenta.setText(pro.getNombre());
                    txtStockVenta1.setText(String.valueOf(pro.getStock()));
                    txtPrecioVenta.setText(String.valueOf(pro.getPrecio()));
                    txtCantidadVenta.requestFocus();

                } else {
                    txtDescripcionVenta.setText("");
                    txtStockVenta1.setText("");
                    txtPrecioVenta.setText("");
                    txtCodigoVenta.requestFocus();
                }

            } else {
               JOptionPane.showMessageDialog(null, "ingrese el codigo del producto");
               txtCodigoVenta.requestFocus();
            }
        }
    }//GEN-LAST:event_txtCodigoVentaKeyPressed

    private void btnNuevoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoProductoActionPerformed
        limpiarCamposProductos();
        txtCodigoProducto.requestFocus();
    }//GEN-LAST:event_btnNuevoProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sistemaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sistemaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sistemaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sistemaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sistemaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnIniciarSesion;
    private javax.swing.JLabel JlabelIdCliente;
    private javax.swing.JTable TableGenerarVenta;
    private javax.swing.JButton btnEditarCliente;
    private javax.swing.JButton btnEditarProducto;
    private javax.swing.JButton btnEditarProveedor;
    private javax.swing.JButton btnEliminarCliente;
    private javax.swing.JButton btnEliminarProducto;
    private javax.swing.JButton btnEliminarProveedor;
    private javax.swing.JButton btnEliminarVenta;
    private javax.swing.JButton btnGuardarCliente;
    private javax.swing.JButton btnGuardarProducto;
    private javax.swing.JButton btnGuardarProveedor;
    private javax.swing.JButton btnImprimirVenta;
    private javax.swing.JButton btnNuevoCliente;
    private javax.swing.JButton btnNuevoProducto;
    private javax.swing.JButton btnNuevoProveedor;
    private javax.swing.JButton btnPDfVenta;
    private javax.swing.JComboBox<String> comboboxProductoProveedor;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelIdProducto;
    private javax.swing.JLabel jLabelIdProveedor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane8;
    private javax.swing.JLabel labelTotalapagar;
    private javax.swing.JTable tableCliente;
    private javax.swing.JTable tableProducto1;
    private javax.swing.JTable tableProveedor;
    private javax.swing.JTable tableVenta;
    private javax.swing.JTextField txtCantidadProducto;
    private javax.swing.JTextField txtCantidadVenta;
    private javax.swing.JTextField txtCedulaCliente;
    private javax.swing.JTextField txtCodigoProducto;
    private javax.swing.JTextField txtCodigoVenta;
    private javax.swing.JTextField txtDescripcionProducto;
    private javax.swing.JTextField txtDescripcionVenta;
    private javax.swing.JTextField txtDireccionCliente;
    private javax.swing.JTextField txtDireccionProveedor;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JTextField txtIdProducto;
    private javax.swing.JTextField txtIdProveedor;
    private javax.swing.JTextField txtIdVenta;
    private javax.swing.JTextField txtNitProveedor;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtNombreClienteVenta;
    private javax.swing.JTextField txtNombreProveedor;
    private javax.swing.JTextField txtPrecioProducto;
    private javax.swing.JTextField txtPrecioVenta;
    private javax.swing.JTextField txtRazonsocialCliente;
    private javax.swing.JTextField txtRazonsocialProveedor;
    private javax.swing.JTextField txtRucVenta;
    private javax.swing.JTextField txtStockVenta;
    private javax.swing.JTextField txtStockVenta1;
    private javax.swing.JTextField txtTelefonoCliente;
    private javax.swing.JTextField txtTelefonoProveedor;
    // End of variables declaration//GEN-END:variables

    public void limpiarCamposCliente() {
        txtIdCliente.setText("");
        txtCedulaCliente.setText("");
        txtNombreCliente.setText("");
        txtTelefonoCliente.setText("");
        txtDireccionCliente.setText("");
        txtRazonsocialCliente.setText("");
    }

    public void limpiarCamposProveedor() {
        txtIdProveedor.setText("");
        txtNitProveedor.setText("");
        txtNombreProveedor.setText("");
        txtTelefonoProveedor.setText("");
        txtDireccionProveedor.setText("");
        txtRazonsocialProveedor.setText("");
    }

    public void limpiarCamposProductos() {
        txtCodigoProducto.setText("");
        txtDescripcionProducto.setText("");
        comboboxProductoProveedor.setSelectedItem(0);
        txtCantidadProducto.setText("");
        txtPrecioProducto.setText("");
    }

}
